resources:
  jobs:
    bronze:
      name: Bronze Pipeline

      parameters:
        - name: entities
          default: customers
        - name: wheel_path
          default: ${workspace.root_path}/artifacts/.internal

      tasks:
        - task_key: bronze

          notebook_task:
            notebook_path: ../../notebooks/bronze/ingest_sources.ipynb
