resources:
  jobs:
    bronze_validate:
      name: Bronze Validate Pipeline

      parameters:
        - name: entities
          default: customers
        - name: wheel_path
          default: ${workspace.root_path}/artifacts/.internal

      tasks:
        - task_key: bronze_validate

          notebook_task:
            notebook_path: ../../notebooks/bronze/validate_bronze.ipynb
