from decimal import Decimal

from faker import Faker

from simulator.domain.catalog.product_model import Product


class ProductGenerator:
    _BRANDS = (
        "Samsung",
        "Apple",
        "LG",
        "Dell",
        "Lenovo",
        "Philips",
        "Sony",
        "Motorola",
        "Xiaomi",
        "Asus",
    )

    _PRODUCTS = (
        "Smartphone",
        "Notebook",
        "Smart TV",
        "Monitor",
        "Mouse",
        "Keyboard",
        "Headset",
        "Printer",
        "Tablet",
        "Smartwatch",
    )

    def __init__(self) -> None:
        self._faker = Faker("pt_BR")

    def generate(
        self,
        seller_id,
        category_id,
    ) -> Product:
        brand = self._faker.random_element(self._BRANDS)
        product_name = self._faker.random_element(self._PRODUCTS)

        return Product.create(
            seller_id=seller_id,
            category_id=category_id,
            sku=self._faker.unique.bothify("SKU-########"),
            name=f"{brand} {product_name}",
            description=f"{brand} {product_name} generated by Marketplace Simulator",
            brand=brand,
            price=Decimal(
                str(
                    round(
                        self._faker.pyfloat(
                            min_value=50,
                            max_value=15000,
                            right_digits=2,
                        ),
                        2,
                    )
                )
            ),
            weight=Decimal(
                str(
                    round(
                        self._faker.pyfloat(
                            min_value=0.10,
                            max_value=25.00,
                            right_digits=3,
                        ),
                        3,
                    )
                )
            ),
            height=Decimal(
                str(
                    round(
                        self._faker.pyfloat(
                            min_value=2,
                            max_value=120,
                            right_digits=2,
                        ),
                        2,
                    )
                )
            ),
            width=Decimal(
                str(
                    round(
                        self._faker.pyfloat(
                            min_value=2,
                            max_value=120,
                            right_digits=2,
                        ),
                        2,
                    )
                )
            ),
            length=Decimal(
                str(
                    round(
                        self._faker.pyfloat(
                            min_value=2,
                            max_value=120,
                            right_digits=2,
                        ),
                        2,
                    )
                )
            ),
        )
